services:

  actual-ai:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: npm run dev-docker
    env_file:
      - .env
    volumes:
      - .:/opt/node_app/app
      - ./package.json:/opt/node_app//package.json
      - ./package-lock.json:/opt/node_app//package-lock.json
      - notused:/opt/node_app/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  notused:
